### ISSUE TITLE
Multiple SmartQL mutations serialised into a single WASM string.

### ISSUE THREAD

**Issue by pur3miish** [pur3miish/smartql#5]
When SmartQL pushes multiple actions to the blockchain in one query it is not combined into single WASM string.
This prevents us from using the newaccount mutation on the [eosio](https://relocke.io/smartql/eosio) smart contract.

Since a new account requires allocation of network resources.

<img width="1419" alt="Screen Shot 2021-04-18 at 11 28 02 am" src="https://user-images.githubusercontent.com/16223777/115131153-24729080-a039-11eb-9232-5b0663aea9cb.png">

I am thinking that that [data loader](https://github.com/graphql/dataloader) might be a way to solve this issue.

**Comment by jaydenseric** [comment]
In GraphQL, unlike using `query` which resolves sibling fields in parallel, `mutation` guarantees the top level fields are executed in sequence. This means, you can run multiple mutations in one request. The limitation is, GraphQL doesn't have a built-in way to pass the result of one top level mutation into the following one as arguments (although there have been proposals).

All the mutations can read from the variables however, so maybe that's all you need in this case? I don't really understand the mutations you're discussing, but maybe you can just put them all into the one query.

**Comment by pur3miish** [comment]
@jaydenseric The fact that `mutations` guarantees top level fields are executed first actually means that this problem can be solved. 

The problem exists at the graphql resolvers, for each mutation field it attempts to push a single serialised transaction to the blockchain.
#### *Figure 1 - Mutations for the creation of a new account and the allocation of RAM.*
<img width="919" alt="Screen Shot 2021-04-18 at 12 04 41 pm" src="https://user-images.githubusercontent.com/16223777/115131812-43bfec80-a03e-11eb-824a-77b5e14233f1.png">

The EOS blockchain can only create an account that has some network resources allocated towards it.
So in *figure 1* I am creating a new account and attempting to allocate some RAM for that account.
So two mutations are needed, but this is the problem, the output of these mutations are serialised to a hex string and need to be in one fetch request to the blockchain, the resolvers are currently attempting to send two fetch requests, one for the new account and one for the allocation of RAM.

So I need to combine the output of the two mutations into a single output and push that to the blockchain.
The blockchain will reject the creation of a new account if RAM is also not allocated to it, so 
Currently my resolvers are sending two transactions for the two mutations, but I need to combine the web assembly hex strings into a single string and push one mutation / action to the blockchain. 

Please see figure 2 and 3 for an illustration of the problem and the proposed solution respectively.

#### *Figure 2* - Rejected by the blockchain as it expects one concatenated request. 
<img width="534" alt="Screen Shot 2021-04-18 at 12 18 06 pm" src="https://user-images.githubusercontent.com/16223777/115132057-2429c380-a040-11eb-8ef2-70b11a6ae3df.png">

#### *Figure 3* Proposed solution
<img width="772" alt="Screen Shot 2021-04-18 at 12 17 21 pm" src="https://user-images.githubusercontent.com/16223777/115132032-08beb880-a040-11eb-84b6-5fcb2a16e0e9.png">

My thoughts are data loader may be able to be used.

**Comment by pur3miish** [comment]
Perhaps the creation of an additional mutation that takes an array of current mutations and serialises that into a single transaction might be an approach.

```graphql
mutation {
  actions([
   newaccount(…),
   buyrambytes(…)
  ]) {
    transaction_id
  }
}
```

That way developers using the API could distinguish between multiple single transactions or create a combination of multiple transactions into one query that the blockchain can handle.
