### ISSUE TITLE
Create an example repo.

### ISSUE THREAD

**Issue by pur3miish** [pur3miish/smartql#6]
Create an example repo for SmartQL mutations and queries.

**Comment by cuvialabs** [comment]
I would like to see the following examples

- [ ] Connecting to different EOSIO chains
- [ ] User signed transactions
- [ ] Creating a new account for a user 
- [ ] Multisig transactions
- [ ] Making and ABI call on a given contract
- [ ] Creating a token
- [ ] Funding and Managing a system treasury
- [ ] 8/ Creating an NFT (dgoods)

**Comment by pur3miish** [comment]
Alright I've added an example on how to create a new account. 

Sorry for the delay, it's been a busy month.
