### ISSUE TITLE
Examples app login is not working

### ISSUE THREAD

**Issue by cuvialabs** [pur3miish/smartql#8]
Doesn't validate correct EOS account names,   tried cuvialabseos

https://www.bloks.io/account/cuvialabseos

**Comment by pur3miish** [comment]
> Doesn't validate correct EOS account names, tried cuvialabseos
> 
> https://www.bloks.io/account/cuvialabseos

Thanks I will get to this soon, I have been creating a digital signature package for SmartQL.
It has been taxing my time.

**Comment by pur3miish** [comment]
> Doesn't validate correct EOS account names, tried cuvialabseos

I deployed [SmartQL@6](https://smartql.relocke.io) API feel free to try and use it.

<img width="1343" alt="Screen Shot 2021-10-04 at 3 35 12 pm" src="https://user-images.githubusercontent.com/16223777/135799391-a898395d-e4c4-44af-abf4-0078180f49f0.png">

Your account appears to be there.

### node.js example

```js
import fetch from "node-fetch"

fetch('https://eos.relocke.io', {
  method: 'post',
  headers: {
    'content-type': 'application/json'
  },
  body: JSON.stringify({
    query: `{
      account_information{
         get_account(account_name: "cuvialabseos") {
             account_name
             core_liquid_balance
              ram_quota
              net_weight
              cpu_weight
              ram_usage
              last_code_update
              total_resources {
                  owner
                  net_weight
                  cpu_weight
                   ram_bytes
               }
              voter_info {
                owner
                proxy
                staked
              }
          }
      }
}`
  })
})
  .then(res => res.json())
  .then(({ data }) => console.log(data))

```
If you encounter a bug in the graphiql IDE with LHS not loading just hard reset to fix it. 

Let me know how you go.
